In [11]:
import numpy as np
import pandas as pd

In [5]:
array = np.zeros ((4,3)) #! Creates an array of zeros
array
one = np.ones((4,3)) #! Creates an array of ones
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
for i in range(3):
    for j in range(3):
        array[i][j] = input(f'Please enter the array[{i}][{j}]')
array

array([[  32.,   32., 3232.],
       [  32.,   32.,   32.],
       [  32.,   32.,   32.],
       [   0.,    0.,    0.]])

In [8]:
array.reshape(12) #! reshaped to 1d array

array([  32.,   32., 3232.,   32.,   32.,   32.,   32.,   32.,   32.,
          0.,    0.,    0.])

In [9]:
array.reshape(3,4) #! reshaped into a different form of 2d array

array([[  32.,   32., 3232.,   32.],
       [  32.,   32.,   32.,   32.],
       [  32.,    0.,    0.,    0.]])

In [10]:
array.reshape(2,2,3) #! reshaped into a 3d array

array([[[  32.,   32., 3232.],
        [  32.,   32.,   32.]],

       [[  32.,   32.,   32.],
        [   0.,    0.,    0.]]])